# Generated by Django 4.1 on 2022-08-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_stripe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
