# Generated by Django 4.1 on 2022-08-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subscription_type',
            field=models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('enterprise', 'enterprise')], default='basic', max_length=10),
            preserve_default=False,
        ),
    ]
