# Generated by Django 4.1 on 2022-08-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
