# Generated by Django 4.1 on 2022-08-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="productSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_stripe_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_stripe_price_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "i_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
