# Generated by Django 4.1 on 2022-08-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_subscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstripemapping",
            name="currency",
            field=models.CharField(default="USD", max_length=256),
        ),
        migrations.AddField(
            model_name="productstripemapping",
            name="product_interval",
            field=models.CharField(
                choices=[("month", "month"), ("week", "week"), ("day", "day")],
                default="day",
                max_length=10,
            ),
        ),
    ]
