# Generated by Django 4.1 on 2022-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_subscription', '0002_productstripemapping_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled')], default='active', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productstripemapping',
            name='product_interval',
            field=models.CharField(choices=[('month', 'month'), ('week', 'week'), ('day', 'day')], default='month', max_length=10),
        ),
    ]
