# Generated by Django 4.1 on 2022-08-09 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_alter_product_name'),
        ('stripe_subscription', '0003_userproductsubscription_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_start', models.DateTimeField()),
                ('subscription_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled')], max_length=10)),
                ('subscription_type', models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('enterprise', 'enterprise')], max_length=10)),
                ('i_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('i_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='userproductsubscription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userproductsubscription',
            name='product',
        ),
        migrations.DeleteModel(
            name='UpComingSubscription',
        ),
        migrations.DeleteModel(
            name='UserProductSubscription',
        ),
    ]
