# Generated by Django 4.1 on 2022-08-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_subscription', '0005_remove_usersubscription_subscription_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscription_end',
            new_name='subscription_end_date',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscription_start',
            new_name='subscription_start_date',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='status',
            new_name='subscription_status',
        ),
    ]
