# Generated by Django 4.1 on 2022-08-09 01:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_user', '0002_rename_stripeuserid_stripeuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeUser',
            new_name='UserStripeMapping',
        ),
    ]
